baseurl: "/ErikasBlog"   # place folder name if the site is served in a subfolder
url: "https://eezife-wustl.github.io"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "authors"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"